### ISSUE TITLE
minetest.is_creative_enabled gets erroneously called with player object instead of name,

### ISSUE THREAD

**Issue by corarona** [ElCeejo/creatura#17]
tl;dr https://github.com/ElCeejo/creatura/blob/main/api.lua#L448 needs to call it with the name otherwise it breaks any implementation that does something with the argument (like mcl2)

now i would not actually expect creatura to work with mcl2 but this one is your fault :P

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6417

```
AsyncErr: Lua: Runtime error from mod '??' in callback luaentity_Punch(): ...inetest/games/mineclone2/mods/HUD/mcl_inventory/init.lua:200: bad argument #1 to 'get_player_by_name' (string expected, got userdata)
stack traceback:
    [C]: in function 'get_player_by_name'
    ...inetest/games/mineclone2/mods/HUD/mcl_inventory/init.lua:200: in function 'is_creative_enabled'
    /home/.../.minetest/mods/creatura/api.lua:461: in function 'basic_punch_func'
    /home/.../.minetest/mods/animalia/mobs/chicken.lua:198: in function </home/.../.minetest/mods/animalia/mobs/chicken.lua:197>
```

originally reported by Faerraven on mcl2 discord

**Comment by corarona** [comment]
kind of ironic that it fails because we're trying to get the object with get_player_by_name lol

**Comment by ElCeejo** [comment]
Fixed as of latest commit.
